### ISSUE TITLE
How can I call Lua procedure

### ISSUE THREAD

**Issue by mbaumsti** [nalilord/TLua#3]
for calling Lua function I found the solution of use ExecuteDirect :
Exemple :
Lua.ExecuteDirect(luaMajProc + '(); ');

But this solution is not very safe and I cannot receive result (or with the stack ?)
I see that you have a TLuaFunction class but I don't know if I can use for this ?
What's the better solution for you ?

Thank you for your help

**Comment by nalilord** [comment]
Sorry, there is no code for the scenario at the moment.

**Comment by mbaumsti** [comment]
Hello
Thank you very much
I will test it

**Comment by mbaumsti** [comment]
That work
I suggest just a modification : 
introduce the function only if it has not already been introduced

**Comment by nalilord** [comment]
What? You can call ` Lua.IntroduceFunction` as many times as you want, if the name is in use nothing will happen, in fact you will get `False` as a result.

**Comment by nalilord** [comment]
> What? You can call ` Lua.IntroduceFunction` as many times as you want, if the name is in use nothing will happen, in fact you will get `False` as a result.

Okay, that was the expected behavior, but there was a "<=" instead of "<", don't know if you meant that but it's fixed now!

**Comment by mbaumsti** [comment]
Yes the problem is solved
Thank you
